baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: hugo-profile
menu:
  main:
    - identifier: Home
      name: Home
      weight: 2
      url: "/home"
    - identifier: Services
      name: Services
      url: "/Services"
      weight : 3
    - identifier: Portfolio
      name: Portfolio
      weight : 4
      url: "/Portfolio"
    - identifier: Careers
      name: Careers
      weight: 5
      url: "/Careers/"
    - identifiers: Contact Us
      name: Contact us
      weight: 6
      url: "/contact/"

